
#
# Toplevel Makefile for libxc/Linux
#
#

# Harmless in Linux, needed for Windows
MINGW_LOCATION?=/

# Should already be set, doesn't hurt to do it twice.
PLATFORM=$(shell posix/platform_name.sh)
RM=rm -rfv
CAT=cat
MKDIR=mkdir -p
DS=/
CP=cp -Rv
LN=ln -s

CFLAGS+=-fPIC
LDEXTRAFLAGS+= -ldl
include Makefile.inc

all: $(OUTPUT_LIBS) $(MAINPROGS) $(INCDIR)
	for X in $(HEADERS); do\
		$(MKDIR) $(INCDIR)/`dirname $$X` && cp -v $$X $(INCDIR)/`dirname $$X`;\
			done

